<a href="https://colab.research.google.com/github/Yosingh1/Machine_Learning/blob/main/Decission_Tree_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV

In [13]:
# import iris dataset from dataset

from sklearn.datasets import load_iris

In [15]:
iris_data=load_iris()

In [16]:
target=iris_data.target

In [17]:
iris_data= load_iris()

In [18]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [19]:
data= iris_data.data

In [20]:
x_train,x_test,y_train,y_test= train_test_split(data, target, test_size=0.30)

In [21]:
print(len(x_train))
print(len(x_test))
print(len(y_train))
print(len(y_test))

105
45
105
45


In [22]:
model= DecisionTreeClassifier()

In [23]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [24]:
pred= model.predict(x_test)

In [25]:
pred

array([0, 1, 2, 2, 0, 0, 1, 0, 1, 2, 0, 0, 2, 0, 2, 0, 1, 1, 1, 1, 1, 1,
       1, 2, 1, 1, 1, 0, 2, 0, 1, 0, 1, 1, 2, 2, 2, 2, 0, 2, 2, 1, 2, 2,
       2])

In [26]:
acc= accuracy_score(y_test,pred)

In [27]:
acc

0.9333333333333333

In [28]:
# grid_search=GridSearchCV()

In [29]:
param_grid={"max_depth":[3,4,5,6],
            "min_samples_split":[2,3,4,5],
            "min_samples_leaf":[1,4,3,5]}

In [30]:
grid_search=GridSearchCV(estimator=model, param_grid=param_grid)

In [31]:
grid_search.fit(x_train,y_train)

GridSearchCV(estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [3, 4, 5, 6],
                         'min_samples_leaf': [1, 4, 3, 5],
                         'min_samples_split': [2, 3, 4, 5]})

In [32]:
grid_search.best_estimator_

DecisionTreeClassifier(max_depth=3)

In [33]:
grid_search.best_params_

{'max_depth': 3, 'min_samples_leaf': 1, 'min_samples_split': 2}

In [34]:
model2= DecisionTreeClassifier(max_depth=3,min_samples_leaf=1,min_samples_split=2)

In [35]:
model2.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=3)

In [37]:
pred2= model2.predict(x_test)

In [38]:
pred2

array([0, 1, 2, 2, 0, 0, 1, 0, 1, 2, 0, 0, 2, 0, 2, 0, 1, 1, 1, 1, 1, 1,
       1, 2, 1, 1, 1, 0, 2, 0, 1, 0, 1, 1, 2, 2, 2, 2, 0, 2, 2, 1, 2, 2,
       2])

In [39]:
acc2= accuracy_score(y_test,pred2)

In [40]:
acc2

0.9333333333333333