<a href="https://colab.research.google.com/github/Yosingh1/Machine_Learning/blob/main/encoding_nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import pandas as pd
import sklearn
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [5]:
data= pd.DataFrame({"text":["people watch ineuron", "ineuron watch ineuron","people write comment", "ineuron write comment"],"output":[1,1,0,0]})

In [6]:
data

text  output
0   people watch ineuron       1
1  ineuron watch ineuron       1
2   people write comment       0
3  ineuron write comment       0

#Bag of Words

In [8]:
# Create the CountVectorizer
vectorizer = CountVectorizer()


In [10]:
document_matric=vectorizer.fit_transform(data["text"])

In [11]:
vectorizer.vocabulary_. #here 0,1,2,3,4 is indexing not count of word

{'people': 2, 'watch': 3, 'ineuron': 1, 'write': 4, 'comment': 0}

In [12]:
document_matric.toarray() # this is the vectors

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

#Ngram

In [14]:
# Create the CountVectorizer
vectorizer_bigram = CountVectorizer(ngram_range=(2,2))

In [15]:
document_matric=vectorizer_bigram.fit_transform(data["text"])

In [16]:
document_matric

<4x6 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [18]:
vectorizer_bigram.vocabulary_

{'people watch': 2,
 'watch ineuron': 4,
 'ineuron watch': 0,
 'people write': 3,
 'write comment': 5,
 'ineuron write': 1}

In [19]:
document_matric.toarray()

array([[0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 1]])

In [22]:
vectorizer_trigram= CountVectorizer(ngram_range=(3,3))
document_matric=vectorizer_trigram.fit_transform(data["text"])
vectorizer_trigram.vocabulary_

{'people watch ineuron': 2,
 'ineuron watch ineuron': 0,
 'people write comment': 3,
 'ineuron write comment': 1}

In [23]:
document_matric.toarray()

array([[0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0]])

In [24]:
vectorizer_unigram_bigram_mix= CountVectorizer(ngram_range=(1,2))
document_matric=vectorizer_unigram_bigram_mix.fit_transform(data["text"])
vectorizer_unigram_bigram_mix.vocabulary_

{'people': 4,
 'watch': 7,
 'ineuron': 1,
 'people watch': 5,
 'watch ineuron': 8,
 'ineuron watch': 2,
 'write': 9,
 'comment': 0,
 'people write': 6,
 'write comment': 10,
 'ineuron write': 3}

In [25]:
document_matric.toarray()

array([[0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0],
       [0, 2, 1, 0, 0, 0, 0, 1, 1, 0, 0],
       [1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1],
       [1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1]])

#TF-IDF

In [27]:
tfidf=TfidfVectorizer()

In [34]:
tf_idf_vector=tfidf.fit_transform(data["text"])
voc=tfidf.vocabulary_
voc

{'people': 2, 'watch': 3, 'ineuron': 1, 'write': 4, 'comment': 0}

In [36]:
voc=tfidf.get_feature_names_out() #2nd way to get voc
voc

array(['comment', 'ineuron', 'people', 'watch', 'write'], dtype=object)

In [32]:
tf_idf_vector.toarray()

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [33]:
tfidf.idf_

array([1.51082562, 1.22314355, 1.51082562, 1.51082562, 1.51082562])