In [1]:
import numpy as np

from statistics import mode

In [4]:
population_data= np.random.randint(10,20,50) #range 10-20 and generate 50 random numbers

In [5]:
population_data

array([16, 17, 16, 12, 16, 14, 12, 10, 15, 16, 18, 15, 14, 19, 17, 14, 16,
       14, 12, 16, 18, 16, 18, 12, 11, 15, 14, 16, 11, 13, 17, 15, 10, 14,
       11, 11, 19, 17, 17, 18, 10, 10, 13, 19, 19, 18, 18, 14, 13, 13])

In [6]:
mean= np.mean(population_data)
mean

14.78

In [7]:
median= np.median(population_data)
median

15.0

In [8]:
mode_= mode(population_data) #mode is not available in numpy, so imprting from statistics
mode_ 

16

In [19]:
print(f"Mean of population data: {np.mean(population_data)}")
print(f"Median of population data: {np.median(population_data)}")
print(f"Mode of population data: {mode(population_data)}")

Mean of population data: 14.78
Median of population data: 15.0
Mode of population data: 16


In [20]:
#generate the sample

sample= np.random.choice(population_data)
sample

17

In [21]:
#generate 20 random sample from population
sample= np.random.choice(population_data,20)
sample

array([19, 17, 14, 15, 12, 14, 10, 14, 18, 15, 16, 18, 11, 16, 18, 11, 16,
       16, 15, 16])

In [22]:
print(f"Mean of Sample data: {np.mean(sample)}")
print(f"Median of Sample data: {np.median(sample)}")
print(f"Mode of Sample data: {mode(sample)}")

Mean of Sample data: 15.05
Median of Sample data: 15.5
Mode of Sample data: 16


In [23]:
sample1= np.random.choice(population_data,20)
sample2= np.random.choice(population_data,20)
sample3= np.random.choice(population_data,20)
sample4= np.random.choice(population_data,20)
print(sample1)
print(sample2)
print(sample3)
print(sample4)

[11 12 14 12 19 18 18 13 16 19 18 14 11 16 18 16 10 19 14 19]
[13 14 18 16 16 10 18 14 18 15 18 17 11 10 16 13 13 16 17 17]
[10 13 14 17 10 18 17 12 13 12 17 15 11 16 18 11 19 11 12 11]
[17 18 16 17 10 12 13 18 12 18 13 18 13 12 13 14 14 16 14 17]


In [24]:
lst_of_mean_of_sample= []
all_sample=[sample1,sample2,sample3,sample4]

for i in all_sample:
    mean=np.mean(i)
    lst_of_mean_of_sample.append(mean)
print(lst_of_mean_of_sample)

[15.35, 15.0, 13.85, 14.75]
